version: '3'

services:

  fastapi:
    build:
      dockerfile: python.dockerfile
    image: ToDo/python
    container_name: python/fastapi
    volumes:
      - ./files:/data/ToDo
    ports:
      - 8000:8000
    networks:
      - app-networks
  
  postgre:
    image: postgres:15
    container_name: pSQL
    entrypoint:
      POSTGRES_DB: "pdb"
      POSTGRES_USER: "kyberlox"
      POSTGRES_PASSWORD: "4179"
    volumes:
      - ./SQL:/var/lib/postgresql/data
      - ./create_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - app-networks



networks:
  app-networks:
    driver: bridge