version: '3'

services:

  postgres:
    image: postgres:15-alpine
    container_name: postgresql
    environment:
      POSTGRES_DB: "pdb"
      POSTGRES_USER: "kyberlox"
      POSTGRES_PASSWORD: "4179"
    volumes:
      - ./pSQL/data:/var/lib/postgresql/data
      - ./pSQL/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
        - app-network
  
  fastapi:
    build:
      dockerfile: python.dockerfile
    image: ToDo/python
    container_name: python/fastapi
    volumes:
      - ./files:/data/ToDo
    ports:
      - 8000:8000
    networks:
      - app-network



networks:
  app-network:
    driver: bridge